"
Clase que modela el sistema
"
Class {
	#name : #CuOOra,
	#superclass : #Object,
	#category : #CuOOra
}

{ #category : #methods }
CuOOra >> altaDislike:post fecha:fechaDate hora:horaTime [
]

{ #category : #methods }
CuOOra >> altaFollow:usuarioASeguir usuarioSeguido:user [
]

{ #category : #methods }
CuOOra >> altaLike:post fecha:fechaDate hora:horaTime [
]

{ #category : #methods }
CuOOra >> altaPregunta:tituloStr descripcion:descripcionStr topicos:topicos fecha:fechaDate hora:horaTime [
]

{ #category : #methods }
CuOOra >> altaRespuesta:descripcionStr fecha:fechaDate hora:horaTime [
]

{ #category : #methods }
CuOOra >> altaTopico:nombreStr descripcion:descripcionStr [
]

{ #category : #methods }
CuOOra >> altaTopicoInteres:unUsuario unTopico:topico [
]

{ #category : #methods }
CuOOra >> altaUsuario:nombreStr contrasenia:contraseniaStr fecha:fechaDate hora:horaTime [
]

{ #category : #methods }
CuOOra >> bajaPregunta: unaPregunta [
]

{ #category : #methods }
CuOOra >> calcularPuntajeUsuario:unUsuario [
]

{ #category : #methods }
CuOOra >> obtenerPreguntasRelevantesUsuario: unUsuario [
]

{ #category : #methods }
CuOOra >> obtenerPreguntasUsuario: unUsuario [
]

{ #category : #methods }
CuOOra >> obtenerRespuestasUsuario: unUsuario [
]
